import type { WorkoutState } from '@/types/workout';

const now = '2026-06-11T00:00:00.000Z';

const defaultProgressionRuleId = 'rule-double-progression-5-10';
const strengthProgressionRuleId = 'rule-double-progression-3-5';

export const initialWorkoutState: WorkoutState = {
  exercises: {
    'bench-press': {
      id: 'bench-press',
      name: 'Bench Press',
      category: 'chest',
      muscleGroup: 'chest',
      defaultUnit: 'kg',
      createdAt: now,
      updatedAt: now,
    },
    'shoulder-press': {
      id: 'shoulder-press',
      name: 'Shoulder Press',
      category: 'shoulders',
      muscleGroup: 'shoulders',
      defaultUnit: 'kg',
      createdAt: now,
      updatedAt: now,
    },
    'lateral-raises': {
      id: 'lateral-raises',
      name: 'Lateral Raises',
      category: 'shoulders',
      muscleGroup: 'shoulders',
      defaultUnit: 'kg',
      createdAt: now,
      updatedAt: now,
    },
    'triceps-pushdown': {
      id: 'triceps-pushdown',
      name: 'Triceps Pushdown',
      category: 'arms',
      muscleGroup: 'triceps',
      defaultUnit: 'kg',
      createdAt: now,
      updatedAt: now,
    },
    'pull-up': {
      id: 'pull-up',
      name: 'Pull-up',
      category: 'back',
      muscleGroup: 'back',
      defaultUnit: 'bodyweight',
      createdAt: now,
      updatedAt: now,
    },
    'barbell-row': {
      id: 'barbell-row',
      name: 'Barbell Row',
      category: 'back',
      muscleGroup: 'back',
      defaultUnit: 'kg',
      createdAt: now,
      updatedAt: now,
    },
    deadlift: {
      id: 'deadlift',
      name: 'Deadlift',
      category: 'back',
      muscleGroup: 'hamstrings',
      defaultUnit: 'kg',
      createdAt: now,
      updatedAt: now,
    },
    curl: {
      id: 'curl',
      name: 'Curl',
      category: 'arms',
      muscleGroup: 'biceps',
      defaultUnit: 'kg',
      createdAt: now,
      updatedAt: now,
    },
    squat: {
      id: 'squat',
      name: 'Squat',
      category: 'legs',
      muscleGroup: 'quads',
      defaultUnit: 'kg',
      createdAt: now,
      updatedAt: now,
    },
    'power-clean': {
      id: 'power-clean',
      name: 'Power Clean',
      category: 'legs',
      muscleGroup: 'full_body',
      defaultUnit: 'kg',
      createdAt: now,
      updatedAt: now,
    },
    'box-jump': {
      id: 'box-jump',
      name: 'Box Jump',
      category: 'legs',
      muscleGroup: 'quads',
      defaultUnit: 'bodyweight',
      createdAt: now,
      updatedAt: now,
    },
    'romanian-deadlift': {
      id: 'romanian-deadlift',
      name: 'Romanian Deadlift',
      category: 'legs',
      muscleGroup: 'hamstrings',
      defaultUnit: 'kg',
      createdAt: now,
      updatedAt: now,
    },
    'leg-press': {
      id: 'leg-press',
      name: 'Leg Press',
      category: 'legs',
      muscleGroup: 'quads',
      defaultUnit: 'kg',
      createdAt: now,
      updatedAt: now,
    },
  },
  programs: {},
  workoutDayTemplates: {},
  programExercises: {},
  workoutSessions: {},
  workoutSets: {},
  progressionRules: {
    [defaultProgressionRuleId]: {
      id: defaultProgressionRuleId,
      name: 'Double Progression 5-10',
      type: 'doubleProgression',
      repMin: 5,
      repMax: 10,
      weightIncrement: 2.5,
      unit: 'kg',
    },
    [strengthProgressionRuleId]: {
      id: strengthProgressionRuleId,
      name: 'Double Progression 3-5',
      type: 'doubleProgression',
      repMin: 3,
      repMax: 5,
      weightIncrement: 2.5,
      unit: 'kg',
    },
  },
  activeWorkoutSessionId: null,
};
