import type { WorkoutState } from '@/types/workout';

const now = '2026-06-11T00:00:00.000Z';

const defaultProgressionRuleId = 'rule-double-progression-8-10';
const strengthProgressionRuleId = 'rule-double-progression-3-5';
const defaultProgramId = 'program-3-day-split';

export const initialWorkoutState: WorkoutState = {
  exercises: {
    'bench-press': {
      id: 'bench-press',
      name: 'Bench Press',
      category: 'chest',
      muscleGroup: 'chest',
      defaultUnit: 'kg',
      createdAt: now,
      updatedAt: now,
    },
    'shoulder-press': {
      id: 'shoulder-press',
      name: 'Shoulder Press',
      category: 'shoulders',
      muscleGroup: 'shoulders',
      defaultUnit: 'kg',
      createdAt: now,
      updatedAt: now,
    },
    'lateral-raises': {
      id: 'lateral-raises',
      name: 'Lateral Raises',
      category: 'shoulders',
      muscleGroup: 'shoulders',
      defaultUnit: 'kg',
      createdAt: now,
      updatedAt: now,
    },
    'triceps-pushdown': {
      id: 'triceps-pushdown',
      name: 'Triceps Pushdown',
      category: 'arms',
      muscleGroup: 'triceps',
      defaultUnit: 'kg',
      createdAt: now,
      updatedAt: now,
    },
    'pull-up': {
      id: 'pull-up',
      name: 'Pull-up',
      category: 'back',
      muscleGroup: 'back',
      defaultUnit: 'bodyweight',
      createdAt: now,
      updatedAt: now,
    },
    'barbell-row': {
      id: 'barbell-row',
      name: 'Barbell Row',
      category: 'back',
      muscleGroup: 'back',
      defaultUnit: 'kg',
      createdAt: now,
      updatedAt: now,
    },
    deadlift: {
      id: 'deadlift',
      name: 'Deadlift',
      category: 'back',
      muscleGroup: 'hamstrings',
      defaultUnit: 'kg',
      createdAt: now,
      updatedAt: now,
    },
    curl: {
      id: 'curl',
      name: 'Curl',
      category: 'arms',
      muscleGroup: 'biceps',
      defaultUnit: 'kg',
      createdAt: now,
      updatedAt: now,
    },
    squat: {
      id: 'squat',
      name: 'Squat',
      category: 'legs',
      muscleGroup: 'quads',
      defaultUnit: 'kg',
      createdAt: now,
      updatedAt: now,
    },
    'power-clean': {
      id: 'power-clean',
      name: 'Power Clean',
      category: 'legs',
      muscleGroup: 'full_body',
      defaultUnit: 'kg',
      createdAt: now,
      updatedAt: now,
    },
    'box-jump': {
      id: 'box-jump',
      name: 'Box Jump',
      category: 'legs',
      muscleGroup: 'quads',
      defaultUnit: 'bodyweight',
      createdAt: now,
      updatedAt: now,
    },
    'romanian-deadlift': {
      id: 'romanian-deadlift',
      name: 'Romanian Deadlift',
      category: 'legs',
      muscleGroup: 'hamstrings',
      defaultUnit: 'kg',
      createdAt: now,
      updatedAt: now,
    },
    'leg-press': {
      id: 'leg-press',
      name: 'Leg Press',
      category: 'legs',
      muscleGroup: 'quads',
      defaultUnit: 'kg',
      createdAt: now,
      updatedAt: now,
    },
  },
  programs: {
    [defaultProgramId]: {
      id: defaultProgramId,
      name: '3-Day Split',
      description: 'Push, Pull, Legs program for progressive overload.',
      dayIds: ['day-push', 'day-pull', 'day-legs'],
      isActive: true,
      phase: 'strength',
      startDate: now,
      createdAt: now,
      updatedAt: now,
    },
  },
  workoutDayTemplates: {
    'day-push': {
      id: 'day-push',
      programId: defaultProgramId,
      name: 'Day 1 - Push',
      order: 1,
      exerciseIds: ['bench-press', 'shoulder-press', 'lateral-raises', 'triceps-pushdown'],
      createdAt: now,
      updatedAt: now,
    },
    'day-pull': {
      id: 'day-pull',
      programId: defaultProgramId,
      name: 'Day 2 - Pull',
      order: 2,
      exerciseIds: ['deadlift', 'pull-up', 'barbell-row', 'curl'],
      createdAt: now,
      updatedAt: now,
    },
    'day-legs': {
      id: 'day-legs',
      programId: defaultProgramId,
      name: 'Day 3 - Legs',
      order: 3,
      exerciseIds: ['squat', 'power-clean', 'box-jump', 'romanian-deadlift', 'leg-press'],
      createdAt: now,
      updatedAt: now,
    },
  },
  programExercises: {
    'program-exercise-bench-press': {
      id: 'program-exercise-bench-press',
      workoutDayTemplateId: 'day-push',
      exerciseId: 'bench-press',
      order: 1,
      targetSets: 3,
      targetRepMin: 8,
      targetRepMax: 10,
      trainingGoal: 'strength',
      targetWeight: 60,
      restSeconds: 180,
      progressionRuleId: defaultProgressionRuleId,
    },
    'program-exercise-shoulder-press': {
      id: 'program-exercise-shoulder-press',
      workoutDayTemplateId: 'day-push',
      exerciseId: 'shoulder-press',
      order: 2,
      targetSets: 3,
      targetRepMin: 8,
      targetRepMax: 10,
      trainingGoal: 'strength',
      targetWeight: 35,
      restSeconds: 150,
      progressionRuleId: defaultProgressionRuleId,
    },
    'program-exercise-lateral-raises': {
      id: 'program-exercise-lateral-raises',
      workoutDayTemplateId: 'day-push',
      exerciseId: 'lateral-raises',
      order: 3,
      targetSets: 3,
      targetRepMin: 12,
      targetRepMax: 15,
      trainingGoal: 'hypertrophy',
      targetWeight: 8,
      restSeconds: 60,
    },
    'program-exercise-triceps-pushdown': {
      id: 'program-exercise-triceps-pushdown',
      workoutDayTemplateId: 'day-push',
      exerciseId: 'triceps-pushdown',
      order: 4,
      targetSets: 3,
      targetRepMin: 10,
      targetRepMax: 12,
      trainingGoal: 'hypertrophy',
      targetWeight: 25,
      restSeconds: 90,
    },
    'program-exercise-deadlift': {
      id: 'program-exercise-deadlift',
      workoutDayTemplateId: 'day-pull',
      exerciseId: 'deadlift',
      order: 1,
      targetSets: 3,
      targetRepMin: 3,
      targetRepMax: 5,
      trainingGoal: 'strength',
      targetWeight: 100,
      restSeconds: 180,
      progressionRuleId: strengthProgressionRuleId,
    },
    'program-exercise-pull-up': {
      id: 'program-exercise-pull-up',
      workoutDayTemplateId: 'day-pull',
      exerciseId: 'pull-up',
      order: 2,
      targetSets: 3,
      targetRepMin: 6,
      targetRepMax: 10,
      trainingGoal: 'hypertrophy',
      restSeconds: 180,
    },
    'program-exercise-barbell-row': {
      id: 'program-exercise-barbell-row',
      workoutDayTemplateId: 'day-pull',
      exerciseId: 'barbell-row',
      order: 3,
      targetSets: 3,
      targetRepMin: 8,
      targetRepMax: 10,
      trainingGoal: 'hypertrophy',
      targetWeight: 55,
      restSeconds: 150,
      progressionRuleId: defaultProgressionRuleId,
    },
    'program-exercise-curl': {
      id: 'program-exercise-curl',
      workoutDayTemplateId: 'day-pull',
      exerciseId: 'curl',
      order: 4,
      targetSets: 3,
      targetRepMin: 10,
      targetRepMax: 12,
      trainingGoal: 'hypertrophy',
      targetWeight: 15,
      restSeconds: 90,
    },
    'program-exercise-squat': {
      id: 'program-exercise-squat',
      workoutDayTemplateId: 'day-legs',
      exerciseId: 'squat',
      order: 1,
      targetSets: 3,
      targetRepMin: 8,
      targetRepMax: 10,
      trainingGoal: 'strength',
      targetWeight: 80,
      restSeconds: 180,
      progressionRuleId: defaultProgressionRuleId,
    },
    'program-exercise-power-clean': {
      id: 'program-exercise-power-clean',
      workoutDayTemplateId: 'day-legs',
      exerciseId: 'power-clean',
      order: 2,
      targetSets: 4,
      targetRepMin: 2,
      targetRepMax: 3,
      trainingGoal: 'power',
      targetWeight: 50,
      restSeconds: 180,
    },
    'program-exercise-box-jump': {
      id: 'program-exercise-box-jump',
      workoutDayTemplateId: 'day-legs',
      exerciseId: 'box-jump',
      order: 3,
      targetSets: 3,
      targetRepMin: 3,
      targetRepMax: 5,
      trainingGoal: 'power',
      targetWeight: 0,
      restSeconds: 120,
    },
    'program-exercise-romanian-deadlift': {
      id: 'program-exercise-romanian-deadlift',
      workoutDayTemplateId: 'day-legs',
      exerciseId: 'romanian-deadlift',
      order: 4,
      targetSets: 3,
      targetRepMin: 8,
      targetRepMax: 10,
      trainingGoal: 'strength',
      targetWeight: 70,
      restSeconds: 150,
      progressionRuleId: defaultProgressionRuleId,
    },
    'program-exercise-leg-press': {
      id: 'program-exercise-leg-press',
      workoutDayTemplateId: 'day-legs',
      exerciseId: 'leg-press',
      order: 5,
      targetSets: 3,
      targetRepMin: 10,
      targetRepMax: 12,
      trainingGoal: 'hypertrophy',
      targetWeight: 120,
      restSeconds: 120,
    },
  },
  workoutSessions: {},
  workoutSets: {},
  progressionRules: {
    [defaultProgressionRuleId]: {
      id: defaultProgressionRuleId,
      name: 'Double Progression 8-10',
      type: 'doubleProgression',
      repMin: 8,
      repMax: 10,
      weightIncrement: 2.5,
      unit: 'kg',
    },
    [strengthProgressionRuleId]: {
      id: strengthProgressionRuleId,
      name: 'Double Progression 3-5',
      type: 'doubleProgression',
      repMin: 3,
      repMax: 5,
      weightIncrement: 2.5,
      unit: 'kg',
    },
  },
  activeWorkoutSessionId: null,
};
